import sindhiImg from './assets/Sindhi-Biryani.jpeg';
import BeefImg from './assets/afganipulao.jpg';
import KormaImg from './assets/qorma.jpg';
import TikkaImg from './assets/tikka.jpg';
import PizzaImg from './assets/pizza.webp';
import BurgerImg from './assets/burger.jpg';
import pastaImg from './assets/pasta.webp'; 
import BerryImg from './assets/smoothie.png';
import AfganiImg from './assets/shawarma.jpg';
import nihariImg from './assets/nihari.jpg';
import seekhImg from './assets/seekh-kabab.jpg';
import CakeImg from './assets/cake.jpg';
const recipes=[
{id:1,name:"sindhi biryani",img:sindhiImg, Ingredients:"  Sindhi biryani is one of Pakistan’s most famous and flavorful dishes, known for its spicy, aromatic, and rich taste. To prepare it, the meat is first marinated with yogurt, red chili powder, turmeric, coriander powder, garam masala, green chilies, ginger-garlic paste, and salt. Then onions are fried until golden, and the marinated meat is added and cooked until the masala is well browned and fragrant. In a separate pot, rice is boiled to about 70% doneness with whole spices like bay leaves, black cardamom, cloves, and cinnamon. When both components are ready, layers of cooked masala and rice are arranged in a pot. On top, saffron or food color, fresh coriander, mint leaves, and fried onions are added before placing it on low heat for 20–25 minutes. This slow steaming allows the rice to absorb all the flavors, resulting in the classic Sindhi biryani—spicy, aromatic, and absolutely delicious.    "},
{id:2,name:"beef pulao",img:BeefImg, Ingredients:"Beef pulao is a hearty, aromatic rice dish known for its rich flavor and perfectly balanced spices. To make it, start by heating oil in a pot and frying sliced onions until they turn golden brown. Add ginger-garlic paste and sauté briefly, then add beef along with salt, black pepper, cumin, coriander powder, whole spices like cinnamon, bay leaves, cloves, and black cardamom. Cook the beef until it changes color, then add water and let it simmer until the meat becomes tender and the yakhni (broth) is rich and flavorful. In another pot, wash and soak basmati rice for about 20 minutes. Once the beef is tender, add the soaked rice directly into the yakhni, ensuring the water level is about one inch above the rice. Cook on medium heat until the water dries, then cover the pot and give it dum for 10–15 minutes on low flame. As the rice steams, it absorbs the savory broth, making the pulao fragrant and deeply flavorful. The final dish is a perfect blend of soft beef, fluffy rice, and warm spices—simple, comforting, and delicious."},
{ id:3,name:"korma",img:KormaImg, Ingredients:" Beef pulao is a hearty, aromatic rice dish known for its rich flavor and perfectly balanced spices. To make it, start by heating oil in a pot and frying sliced onions until they turn golden brown. Add ginger-garlic paste and sauté briefly, then add beef along with salt, black pepper, cumin, coriander powder, whole spices like cinnamon, bay leaves, cloves, and black cardamom. Cook the beef until it changes color, then add water and let it simmer until the meat becomes tender and the yakhni (broth) is rich and flavorful. In another pot, wash and soak basmati rice for about 20 minutes. Once the beef is tender, add the soaked rice directly into the yakhni, ensuring the water level is about one inch above the rice. Cook on medium heat until the water dries, then cover the pot and give it dum for 10–15 minutes on low flame. As the rice steams, it absorbs the savory broth, making the pulao fragrant and deeply flavorful. The final dish is a perfect blend of soft beef, fluffy rice, and warm spices—simple, comforting, and delicious. " },
{id:4,name:"tikka",img:TikkaImg ,Ingredients:"Tikka is a popular, flavorful dish known for its smoky aroma and juicy, tender pieces of meat. To make it, start by cutting chicken or beef into medium-sized cubes. Prepare a marinade using yogurt, lemon juice, ginger-garlic paste, red chili powder, turmeric, crushed red pepper, cumin powder, coriander powder, garam masala, and salt. Add a little oil and mix well until the marinade becomes smooth and thick. Coat the meat pieces completely and let them marinate for at least 2–3 hours, or overnight for best flavor. Once marinated, thread the pieces onto skewers and cook them on a grill, in an oven, or on a stovetop grill pan. Cook until the meat is tender, slightly charred, and smoky on the edges. Brush with a little butter during cooking for extra juiciness. Serve hot with lemon slices, mint chutney, and fresh salad—making a perfect, flavorful tikka that’s spicy, aromatic, and incredibly satisfying. "},
{id:5,name:"pizza",img:PizzaImg,Ingredients:"  To make a delicious homemade pizza, start by preparing the dough. Mix warm water, yeast, a little sugar, salt, olive oil, and all-purpose flour until a soft dough forms. Knead it well and let it rest for 1–2 hours until it doubles in size. Meanwhile, prepare the pizza sauce by cooking tomatoes with garlic, oregano, chili flakes, salt, black pepper, and a little olive oil until it thickens. When the dough is ready, roll it out into a round shape and spread the sauce evenly on top. Add mozzarella cheese generously, then place your favorite toppings such as chicken, pepperoni, olives, capsicum, onions, mushrooms, or sweet corn. Sprinkle a bit more cheese and oregano for extra flavor. Bake the pizza in a preheated oven at 220°C (425°F) for 12–15 minutes or until the crust becomes golden and the cheese melts perfectly. Once done, slice and serve hot—soft, cheesy, and full of classic pizza flavor. " },
{ id:6,name:"Burger",img:BurgerImg, Ingredients: " To make a juicy homemade burger, start by preparing the patty. Mix minced beef or chicken with salt, black pepper, paprika, garlic powder, onion powder, and a little soy sauce or Worcestershire sauce for extra flavor. Shape the mixture into round, thick patties and refrigerate them for 15–20 minutes to help them hold their shape. Heat a grill pan or regular pan with a little oil and cook the patties on medium heat until they are nicely browned and fully cooked from the inside. Toast the burger buns lightly in the same pan for extra crispiness. To assemble the burger, spread mayonnaise or your favorite sauce on the buns, place the cooked patty on the bottom bun, and top it with cheese, lettuce, tomatoes, onions, or pickles. Add ketchup or any extra sauces you like, then close the burger and serve hot. The result is a delicious, juicy burger that’s full of flavor, easy to make, and perfect for any meal."},
{id:7,name:"pasta",img:pastaImg, Ingredients:"  To make a creamy and flavorful pasta, start by boiling your favorite pasta—such as penne or spaghetti—in salted water until it becomes soft but still firm. While the pasta cooks, heat some butter or oil in a pan and sauté chopped garlic until fragrant. Add boneless chicken strips or vegetables if you prefer, and cook until tender. Pour in fresh cream or milk along with a little flour to thicken the sauce. Season it with salt, black pepper, chili flakes, oregano, and a pinch of paprika for extra taste. Once the sauce becomes creamy, add grated cheese and stir until smooth and melted. Drain the boiled pasta and mix it into the sauce, coating every piece evenly. Cook it for a couple of minutes on low heat so the flavors blend well. Serve hot, topped with extra cheese and herbs—rich, creamy, and absolutely comforting. " },
{id:8,name:"Berry Banana Smoothie",img:BerryImg,  Ingredients:" To make a delicious Berry Banana Smoothie, start by adding one ripe banana, a handful of mixed berries—such as strawberries, blueberries, or raspberries—and a cup of cold milk or yogurt into a blender. For extra creaminess, you can also add a few tablespoons of oats or a spoon of peanut butter. Sweeten it with honey or sugar if needed, and add a few ice cubes to make it chilled and refreshing. Blend everything until smooth and creamy, making sure there are no chunks left. Pour the smoothie into a glass and serve immediately. It’s a perfect, healthy drink that’s naturally sweet, full of vitamins, and great for breakfast or a quick energy boost.  " },
{ id:9,name:"Afgani sharwma",img:AfganiImg,Ingredients:"  To make Afghani Shawarma, start by marinating thinly sliced chicken in a mixture of yogurt, lemon juice, ginger-garlic paste, black pepper, salt, cumin powder, coriander powder, and a little bit of green chili paste for mild heat. Add a tablespoon of oil and mix everything well so the chicken absorbs all the flavors. Let it marinate for at least 1–2 hours. Cook the marinated chicken in a pan on medium heat until it becomes tender and slightly golden. For the special Afghani sauce, blend yogurt, mayonnaise, garlic, lemon juice, a pinch of salt, and black pepper until smooth and creamy. Warm soft pita or shawarma bread and spread the Afghani sauce generously on it. Add the cooked chicken, fresh cabbage, onions, cucumbers, and a little more sauce on top. Roll the shawarma tightly and toast it lightly on a pan for a crisp outer layer. The result is a creamy, mildly spiced, and delicious Afghani-style shawarma that’s perfect for any meal.  " },
{id:10,name:"nihari",img:nihariImg, Ingredients:"  To make traditional Nihari, start by heating oil or ghee in a heavy pot and lightly frying sliced onions until golden brown. Add ginger-garlic paste and sauté briefly before adding beef shank or stew meat along with salt, turmeric, red chili powder, coriander powder, and Nihari masala (or a mix of fennel seeds, black pepper, and cardamom). Brown the meat for a few minutes, then add enough water to cover it and let it simmer on low heat for several hours until the meat becomes tender and the broth thickens into a rich, flavorful gravy. Once the meat is soft, mix in a little wheat flour or cornflour dissolved in water to slightly thicken the stew. Garnish with fresh ginger slices, chopped coriander, and green chilies. Serve hot with naan, paratha, or steamed rice. The result is a deeply aromatic, spicy, and hearty Nihari that melts in your mouth and is perfect for breakfast or a special meal.  " },
{id:11,name:"seekh kabab",img:seekhImg, Ingredients:" To make delicious Seekh Kababs, start by taking minced beef or lamb and mixing it with finely chopped onions, green chilies, fresh coriander, ginger-garlic paste, red chili powder, cumin powder, garam masala, salt, and a little chaat masala for extra flavor. Add a small amount of gram flour or bread crumbs to help bind the mixture and mix everything thoroughly until smooth and well combined. Divide the mixture into equal portions and shape them around skewers into long, cylindrical kababs. Preheat a grill or pan, brush lightly with oil, and cook the kababs on medium heat, turning occasionally, until they are browned on all sides and fully cooked inside. For an authentic smoky flavor, you can also cook them over charcoal or use a small piece of hot coal inside the kabab pan (dhungar method). Serve hot with naan, paratha, or pita bread, along with mint chutney, sliced onions, and lemon wedges. The kababs are juicy, aromatic, and full of rich spices—perfect as an appetizer or main dish.  " },
{ id:12,name:"cake",img:CakeImg, Ingredients:"  To make a soft and fluffy cake, start by preheating your oven to 180°C (350°F) and greasing a cake pan. In a bowl, whisk together 1 cup of sugar and 1/2 cup of softened butter until creamy. Add 2 eggs, one at a time, and mix well. In another bowl, sift 1 ½ cups of all-purpose flour with 1 ½ teaspoons of baking powder and a pinch of salt. Gradually add the dry ingredients to the wet mixture, alternating with 1/2 cup of milk, and mix until smooth and lump-free. For extra flavor, add 1 teaspoon of vanilla extract or any flavoring of your choice. Pour the batter into the prepared pan and bake for 25–30 minutes, or until a toothpick inserted in the center comes out clean. Let the cake cool completely before frosting with buttercream, chocolate, or your favorite icing. The result is a soft, moist, and flavorful cake perfect for birthdays, celebrations, or a simple homemade treat."},
]
export default recipes;